apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - 'infra/k8s/*'
build:
  local:
    push: false
  artifacts:
    - image: registry.portavita.net/nkoster/ms1-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: registry.portavita.net/nkoster/ms1-comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: '.'
    - image: registry.portavita.net/nkoster/ms1-event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: '.'
    - image: registry.portavita.net/nkoster/ms1-moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: '.'
    - image: registry.portavita.net/nkoster/ms1-posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: '.'
    - image: registry.portavita.net/nkoster/ms1-query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: '.'
