---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-private
    nginx.ingress.kubernetes.io/use-regex: 'true'
  labels:
    app: nkoster-ingress
  name: nkoster-ingress
  namespace: nkoster
spec:
  rules:
  - host: nkoster.pvdev.portavita.net
    http:
      paths:
      - backend:
          serviceName: nkoster-posts
          servicePort: 4000
        path: /posts/create
      - backend:
          serviceName: nkoster-query
          servicePort: 4002
        path: /posts
      - backend:
          serviceName: nkoster-comments
          servicePort: 4001
        path: /posts/?(.*)/comments
      - backend:
          serviceName: nkoster-client
          servicePort: 3000
        path: /?(.*)
